# Site settings
title: Artistic Walls by Mark H.
email: c***sar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Artistic Walls by Mark H. is a full service interior painting
  company specalizing on faux finishes and murals.  We are located
  in Streamwood, Illinois and service Chicago and the entire 
  Chicagoland area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Mark Hauserman
email: mh*****man@gmail.com
facebook_username: mark_h*****man
twitter_username: artisticwalls_mh
linkedin_username: company-beta/5922601/
instagram_username: artisticwalls_mh
address:
  - line: 301 Irving Park Rd.
  - line: Streamwood, IL, USA
  # Feel free to add more lines here 
telephone: 815-555-1212
copyright: Artistic Walls by Mark H.

# API settings
google_api_key: AIzaSyB64-Q2dF_AHntyYblMaE7D9pXfn7VHBxc

# Build settings
markdown: kramdown
